//! The report: `docs/validation/traffic.md`.

use std::fmt::Write as _;

use crate::Group;
use crate::run::{CheckResult, Verdict};

fn num(v: f64) -> String {
    if v.is_nan() {
        "NaN".to_string()
    } else if v == v.trunc() && v.abs() < 1e9 {
        format!("{v:.0}")
    } else if v.abs() >= 100.0 {
        format!("{v:.1}")
    } else if v.abs() >= 1.0 {
        format!("{v:.3}")
    } else {
        format!("{v:.4}")
    }
}

fn band(b: Option<(f64, f64)>) -> String {
    match b {
        None => "reported".to_string(),
        Some((lo, hi)) if lo == hi => format!("= {}", num(lo)),
        Some((lo, hi)) if hi == f64::INFINITY => format!("≥ {}", num(lo)),
        Some((lo, hi)) if lo == f64::NEG_INFINITY => format!("≤ {}", num(hi)),
        Some((lo, hi)) => format!("{} – {}", num(lo), num(hi)),
    }
}

fn cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

/// Renders the whole report. `command` is the command line that produced it.
pub fn markdown(results: &[CheckResult], command: &str, quick: bool) -> String {
    let mut out = String::new();
    let mut totals = [0usize; 4];
    for r in results {
        for (_, v) in r.verdicts() {
            totals[match v {
                Verdict::Pass => 0,
                Verdict::NotProved => 1,
                Verdict::Fail => 2,
                Verdict::Reported => 3,
            }] += 1;
        }
    }
    let errors = results.iter().filter(|r| r.shipped.is_err()).count();
    let _ = writeln!(out, "# Traffic validation\n");
    let _ = writeln!(
        out,
        "Generated by `{command}`{}. Do not edit by hand: change the check in \
         `crates/v2xw-trafficval` and run the command again.\n",
        if quick { " (quick mode: shorter runs, no Manhattan-scale imports)" } else { "" }
    );
    let _ = writeln!(
        out,
        "Every check below is run as shipped, where each held figure must sit inside its \
         band, and again with each listed **fault injected**, where at least one held figure \
         must leave its band. A held figure that no fault turned red is marked *pass, not \
         proved*: it passed, but the suite has not shown it could fail. A *reported* figure \
         is set beside its reference without a band, because no defensible published \
         tolerance was found for it; the reason is in the reference column.\n"
    );
    let _ = writeln!(
        out,
        "**Summary:** {} checks; held figures: {} pass, {} pass but not proved, {} FAIL; {} \
         reported; {} checks could not run.\n",
        results.len(),
        totals[0],
        totals[1],
        totals[2],
        totals[3],
        errors
    );
    let _ = writeln!(out, "| Check | Verdict | Held figures out of band |");
    let _ = writeln!(out, "|---|---|---|");
    for r in results {
        let v = r.verdicts();
        let fails: Vec<String> = v
            .iter()
            .filter(|(_, v)| *v == Verdict::Fail)
            .map(|(row, _)| cell(&row.metric))
            .collect();
        let verdict = if r.shipped.is_err() {
            "could not run"
        } else if !fails.is_empty() {
            "FAIL"
        } else if v.iter().any(|(_, v)| *v == Verdict::NotProved) {
            "pass, partly not proved"
        } else if v.iter().all(|(_, v)| *v == Verdict::Reported) {
            "reported"
        } else {
            "pass"
        };
        let _ = writeln!(
            out,
            "| [`{}`](#{}) | {} | {} |",
            r.id,
            r.id.replace('/', "").replace('_', "-"),
            verdict,
            if fails.is_empty() { "—".to_string() } else { fails.join("; ") }
        );
    }
    let _ = writeln!(out);
    for g in Group::ALL {
        let group: Vec<&CheckResult> = results.iter().filter(|r| r.group == g).collect();
        if group.is_empty() {
            continue;
        }
        let _ = writeln!(out, "## {}\n", g.title());
        for r in group {
            let _ = writeln!(out, "### {}\n", r.id);
            let _ = writeln!(out, "**{}**\n", r.title);
            let _ = writeln!(out, "{}\n", r.procedure);
            match &r.shipped {
                Err(e) => {
                    let _ = writeln!(out, "**Could not run:** {}\n", cell(e));
                }
                Ok(o) => {
                    let _ = writeln!(
                        out,
                        "| Figure | Measured | n | Band | Reference | Verdict | Red under fault |"
                    );
                    let _ = writeln!(out, "|---|---|---|---|---|---|---|");
                    for (row, v) in r.verdicts() {
                        let proved = r.proved_by(&row.metric);
                        let _ = writeln!(
                            out,
                            "| {} | {} | {} | {} | {} | {} | {} |",
                            cell(&row.metric),
                            num(row.measured),
                            row.samples.map(|n| n.to_string()).unwrap_or_else(|| "—".into()),
                            band(row.band),
                            cell(&row.reference),
                            v.label(),
                            if !row.tested() {
                                "—".to_string()
                            } else if proved.is_empty() {
                                "none".to_string()
                            } else {
                                proved.iter().map(|k| k.to_string()).collect::<Vec<_>>().join(", ")
                            }
                        );
                    }
                    let _ = writeln!(out);
                    for n in &o.notes {
                        let _ = writeln!(out, "- {}", n.replace('\n', " "));
                    }
                    if !o.notes.is_empty() {
                        let _ = writeln!(out);
                    }
                }
            }
            if !r.faults.is_empty() {
                let _ = writeln!(out, "Faults injected:\n");
                for (k, f) in r.faults.iter().enumerate() {
                    let what = match &f.outcome {
                        Err(e) => format!("could not run: {}", cell(e)),
                        Ok(o) => {
                            let red: Vec<String> = o
                                .rows
                                .iter()
                                .filter(|row| row.tested() && !row.passes())
                                .map(|row| format!("{} = {}", row.metric, num(row.measured)))
                                .collect();
                            if red.is_empty() {
                                "nothing went red".to_string()
                            } else {
                                format!("red: {}", red.join("; "))
                            }
                        }
                    };
                    let _ = writeln!(out, "{}. {} — {}", k + 1, f.fault, what);
                }
                let _ = writeln!(out);
            }
        }
    }
    out
}
