#!/usr/bin/env python3
"""An independent UPER implementation checking the ETSI messages this crate encodes.

The CAM, DENM and VAM encoders are generated by ``rasn-compiler`` from the committed ETSI
forge modules; nothing independent had checked their octets. ``asn1tools`` compiles the
same committed modules (``third_party/asn1/etsi``) with its own parser and its own UPER
codec, so for each vector this script

1. decodes the Rust octets with asn1tools — which catches octets a second implementation
   of the standard cannot read;
2. re-encodes what it decoded and compares the octets with Rust's — which catches any
   bit asn1tools would have written differently;
3. returns the decoded value, so the Rust test can check fields it cares about (a DENM's
   sub-cause, a CAM path's chained deltas).

(``pycrate`` was tried first and cannot parse the Release 2 CDD's inner subtyping —
``BasicLaneInformation`` — so asn1tools is the oracle here.)

Usage: ``etsi_oracle.py <etsi asn1 root> <vectors.json> <results.json> [extra modules...]``
where each vector is ``{"name", "pdu", "rust_hex"}``.
"""

from __future__ import annotations

import json
import os
import sys
import traceback

import asn1tools

MODULES = [
    "normalized-utf8/cdd_ts102894_2/ETSI-ITS-CDD.asn",
    "cam_ts103900/CAM-PDU-Descriptions.asn",
    "denm_ts103831/DENM-PDU-Descriptions.asn",
    "vam_ts103300_3/VAM-PDU-Descriptions.asn",
]


def jsonable(v):
    if isinstance(v, (bytes, bytearray)):
        return {"__hex__": bytes(v).hex()}
    if isinstance(v, tuple):
        # CHOICE -> [name, value]; BIT STRING -> [bytes, nbits]
        if len(v) == 2 and isinstance(v[0], str):
            return {"__choice__": [v[0], jsonable(v[1])]}
        return [jsonable(x) for x in v]
    if isinstance(v, dict):
        return {k: jsonable(x) for k, x in v.items()}
    if isinstance(v, list):
        return [jsonable(x) for x in v]
    return v


def main() -> int:
    root, vectors_path, results_path = sys.argv[1:4]
    extra = sys.argv[4:]
    spec = asn1tools.compile_files([os.path.join(root, m) for m in MODULES + extra], "uper")
    vectors = json.load(open(vectors_path, encoding="utf-8"))
    results = []
    for v in vectors:
        r = {"name": v["name"], "pdu": v["pdu"]}
        try:
            raw = bytes.fromhex(v["rust_hex"])
            decoded = spec.decode(v["pdu"], raw)
            again = spec.encode(v["pdu"], decoded).hex()
            r["py_hex"] = again
            r["encode_match"] = again == v["rust_hex"]
            r["decoded"] = jsonable(decoded)
        except Exception as exc:  # noqa: BLE001 - the report is the point
            r["error"] = f"{type(exc).__name__}: {exc}"
            r["traceback"] = traceback.format_exc(limit=3)
        results.append(r)
    json.dump({"results": results}, open(results_path, "w", encoding="utf-8"))
    bad = [r for r in results if r.get("error") or not r.get("encode_match")]
    print(f"{len(results) - len(bad)}/{len(results)} vectors matched asn1tools")
    for b in bad[:5]:
        print("  MISMATCH", json.dumps({k: x for k, x in b.items() if k != "decoded"})[:400])
    return 0


if __name__ == "__main__":
    sys.exit(main())
